name: Test Runner
on: [push]
permissions:
  contents: write
jobs:
  checkout:
    runs-on: lv2020
    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: astemes
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ steps.app-token.outputs.token }}
  test:
    needs: checkout
    runs-on: lv2020
    steps:
      - uses: astemes/astemes-github-actions/runLUnit@main
        with:
          project-path: "source\\LUnit Framework.lvproj"
  build:
    needs: test
    runs-on: lv2020
    steps:
      - uses: astemes/astemes-github-actions/buildLVBuildSpec@main
        with:
          project-path: "source\\LUnit Framework.lvproj"
          build-spec: "LUnit"
      - name: Build MKDocs
        uses: astemes/astemes-github-actions/buildDocs@main
        with:
            project-title: "LUnit"
            author: "Anton Sundqvist"
            initial-release: "2025"
  release:
    needs: build
    runs-on: lv2020
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Get version
        id: get_version
        uses: astemes/astemes-github-actions/getVersion@main
      - name: Build VIP
        id: build-vip
        uses: astemes/astemes-github-actions/buildVIPackage@main
        with:
          vipb-path: "source\\LUnit.vipb"
          lv-version: "20.0"
          pkg-version: "${{ steps.get_version.outputs.version }}"
      - name: Release VIP
        uses: astemes/astemes-github-actions/releaseFile@main
        with:
          file-path: "${{ steps.build-vip.outputs.vip-path }}"
      - name: Deploy GHPages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          python -m mkdocs gh-deploy --force
        shell: powershell